### ISSUE TITLE
Missing "0" for Contact Number

### ISSUE THREAD

**Issue by DrtLckd** [Jade013/LeninSystem_RFQ#7]
Any contact number that starts with "0" has the 0 omitted in the database

![image](https://github.com/user-attachments/assets/c38a4475-a5e8-41c2-9b25-19d699a249d4)

**Comment by Jade013** [comment]
![image](https://github.com/user-attachments/assets/63d86102-1e13-431a-b239-13f8dbd8a912)

Issue closed.
